- astro.config.mjs
Allows us to track across subdomains.
See https://plausible.io/blog/conversion-attribution-across-domain-subdomains
> chore: Adjust Plausible domain

- package-lock.json
- package.json
- src/content/docs/reference/snippets/nodejs/RequestFields.ts
This shows how to use `@arcjet/body` to get the body of a Node.js `IncomingMessage` when manually constructing the request for the SDK.
Closes #27
> fix: add getBody to the RequestFields example

- .github/dependabot.yml
I noticed that all the arcjet packages were updated as separate PRs. I believe this is due to them being in alpha and not receiving major/minor/patch updates.
This will group them together.
> chore(ci): Group all arcjet packages together for version updates

- .devcontainer/devcontainer.json
This adds a devcontainer config to the project. Besides the name, it is a duplicate of https://github.com/arcjet/arcjet-js/blob/main/.devcontainer/devcontainer.json
There are plans to change that devcontainer setup but this is fine for now.
> chore: Add devcontainer to project

- package-lock.json
Dependabot doesn't know how to update dependencies that use `overrides`, so I updated rollup manually.
> deps: Update rollup

- src/content/docs/rate-limiting/reference/nextjs.mdx
- src/content/docs/troubleshooting.mdx
- src/snippets/reference/nextjs/HealthzRouteApp.js
- src/snippets/reference/nextjs/HealthzRouteApp.ts
- src/snippets/reference/nextjs/HealthzRoutePages.js
- src/snippets/reference/nextjs/HealthzRoutePages.ts
Closes #112 
I wasn't able to find anywhere else that included a copy-and-paste example of a middleware with Arcjet, so I included the fix for Next.js.
Please let me know if this should be moved somewhere else, I wasn't able to find a good home for this in the existing ontology so I took a guess.
> feat: add troubleshooting documentation for health probes and Arcjet

- src/content/docs/bot-protection/concepts.mdx
- src/content/docs/bot-protection/identifying-bots.mdx
- src/content/docs/bot-protection/reference/bun.mdx
- src/content/docs/bot-protection/reference/nextjs.mdx
- src/content/docs/bot-protection/reference/nodejs.mdx
- src/content/docs/bot-protection/reference/sveltekit.mdx
Extended example of how to detect the missing user agent error.
> chore: Add example of handling missing user-agent header

- src/styles/docs/index.scss
- src/styles/main.scss
Improved heading styling for h4 and below, eg:
Turns this:
To this:
> fix: improve and differentiate heading style

- src/snippets/get-started/remix/Step3.tsx
This import is unused in our example.
> chore: Remove unused import in Remix docs

- src/snippets/get-started/bun-hono/Step3.mdx
- src/snippets/get-started/bun/Step3.mdx
- src/snippets/get-started/nest-js/Step3.mdx
- src/snippets/get-started/node-js-express/Step3.mdx
- src/snippets/get-started/node-js-hono/Step3.mdx
- src/snippets/get-started/node-js/Step3.mdx
- src/snippets/get-started/remix/Step3.mdx
I think we should instruct the user to create a file where the contents will be in all examples. We currently do this in next and svelte but not in others.
Replaces #185
> chore: Add instruction to create file for all getting started guides

- src/snippets/get-started/bun-hono/Step3.mdx
- src/snippets/get-started/node-js-express/Step3.mdx
- src/snippets/get-started/node-js-hono/Step3.mdx
- src/snippets/get-started/node-js/Step3.mdx
- src/snippets/get-started/sveltekit/Step3.mdx
In discussions with @e-moran, it became apparent that we have to assume the users have scaffolded a project already, so we want to say "update file" when we aren't creating a new file for the framework.
> chore: Update wording about files in getting started

- src/snippets/get-started/nest-js/Step3.mdx
Closes #187
No slots were specified for the NestJS switcher.
> fix: Populate code switcher for NestJS

- src/snippets/bot-protection/quick-start/nodejs/Step4.mdx
- src/snippets/email-validation/quick-start/nodejs/Step4.mdx
- src/snippets/get-started/node-js-express/Step4.mdx
- src/snippets/get-started/node-js/Step4.mdx
- src/snippets/rate-limiting/quick-start/nodejs/Step4.mdx
- src/snippets/shield/quick-start/nodejs/Step4.mdx
- src/snippets/signup-protection/quick-start/nodejs/Step4.mdx
The content in the aside is relevant for `npx tsx` as well as `node` so we should show it to both.
> fix: show aside for tsx too

- src/content/docs/reference/bun.mdx
- src/content/docs/reference/nextjs.mdx
- src/content/docs/reference/nodejs.mdx
- src/content/docs/reference/sveltekit.mdx
The correct method name on the Reason object is `.isError()`, not `.isErrored()`
> fix: correct method name

- src/snippets/get-started/bun-hono/Step4.mdx
- src/snippets/get-started/bun/Step4.mdx
Closes #195
If the `.env.local` file isn't set up correctly, the users might think their app will reload due to `--hot`.
> chore: Add note about bun reload

- src/content/docs/rate-limiting/algorithms.mdx
As pointed out at <https://github.com/arcjet/arcjet-docs/discussions/203#discussioncomment-11155698>
> fix: Correct sliding window calculation

- vercel.json
This needs to go in Vercel config as a redirect rather than Astro because we
already have redirects for non-trailing slash versions, and Astro thinks adding
a trailing slash redirect is the same.
> fix: Redirect trailing slashes

- src/snippets/bot-protection/reference/nextjs/PerRoute.mdx
- src/snippets/sensitive-info/reference/nextjs/PerRoute.mdx
- src/snippets/sensitive-info/reference/nextjs/PerRouteApp.js
- src/snippets/sensitive-info/reference/nextjs/PerRouteApp.ts
The "Per route" code examples were swapped on sensitive info and bot detection.
> fix: sensitive info and bot detection per route examples

- src/snippets/bot-protection/quick-start/bun/Step4.mdx
- src/snippets/bot-protection/quick-start/nextjs/Step4.mdx
- src/snippets/bot-protection/quick-start/nodejs/Step4.mdx
- src/snippets/bot-protection/quick-start/sveltekit/Step4.mdx
The Step 4 for bot detection is different based on the framework.
We either show the framework switcher or don't depending on the framework.
In some examples we don't use a `-i` flag so users won't see the response status.
I also switched some from `-I` to `-i` because `-I` sends a head request.
> fix: sync bot protection step4

- src/content/docs/get-started.mdx
- src/snippets/get-started/bun-hono/Step2.mdx
- src/snippets/get-started/bun/Step2.mdx
- src/snippets/get-started/deno/Step2.mdx
- src/snippets/get-started/nest-js/GlobalGuard.ts
- src/snippets/get-started/nest-js/Step2.mdx
- src/snippets/get-started/next-js/Step2.mdx
- src/snippets/get-started/node-js-express/Step2.mdx
- src/snippets/get-started/node-js-hono/Step2.mdx
- src/snippets/get-started/node-js/Step2.mdx
- src/snippets/get-started/remix/Step2.mdx
- src/snippets/get-started/sveltekit/Step2.mdx
Some frameworks need `.env` instead of `.env.local` (specifically, Deno and anything that uses Vite) so I've moved that sentence into the snippets themselves.
I also re-added the note about non-local IPs since @danni-popova ran into the issue earlier in the week.
> fix: Move env file name to framework snippets for getting started

- src/content/docs/bot-protection/reference.mdx
This refactors the bot protection reference guide to prefix names with the framework and groups them for easier copy-paste.
This also helped me catch a bug where Next.js examples were being used for Identified Bots section.
> chore: Refactor bot reference guide

- src/content/docs/bot-protection/quick-start.mdx
- src/snippets/bot-protection/quick-start/deno/Step1.mdx
- src/snippets/bot-protection/quick-start/deno/Step2.mdx
- src/snippets/bot-protection/quick-start/deno/Step3.mdx
- src/snippets/bot-protection/quick-start/deno/Step3.ts
- src/snippets/bot-protection/quick-start/deno/Step4.mdx
I stacked this on top of #212 so adding the framework was easier with copy-paste.
This adds Deno as a framework in the Bot Protection quick start guide.
> feat: Add Deno Bot Protection Quick Start

- src/content/docs/bot-protection/reference.mdx
- src/snippets/bot-protection/reference/deno/AllowingBots.mdx
- src/snippets/bot-protection/reference/deno/AllowingBots.ts
- src/snippets/bot-protection/reference/deno/DecisionLog.mdx
- src/snippets/bot-protection/reference/deno/DecisionLog.ts
- src/snippets/bot-protection/reference/deno/DenyingBots.mdx
- src/snippets/bot-protection/reference/deno/DenyingBots.ts
- src/snippets/bot-protection/reference/deno/Errors.mdx
- src/snippets/bot-protection/reference/deno/Errors.ts
- src/snippets/bot-protection/reference/deno/Filtering.mdx
- src/snippets/bot-protection/reference/deno/Filtering.ts
- src/snippets/bot-protection/reference/deno/IdentifiedBots.mdx
- src/snippets/bot-protection/reference/deno/IdentifiedBots.ts
This builds upon #216 which made it easier to copy-paste snippets to add the new adapter.
This adds Deno as a framework into the Bot Reference.
> feat: Add Deno adapter in Bot Reference

- src/components/FrameworkLinks.tsx
- src/components/Hero.module.scss
- src/content/docs/get-started.mdx
- src/content/docs/index.mdx
Based on the feedback from one of our developer interviews, this changes the home landing page to drop the user right into the docs.
This reveals the full sidebar immediately so it's one less click to get where you want to go if you already know what you want. It also shows the full depth of the docs to new users.
> chore: Change homepage to drop right into the docs

- src/components/SDKVersionBun.astro
- src/components/SDKVersionNextjs.astro
- src/components/SDKVersionNodejs.astro
- src/components/SDKVersionSvelteKit.astro
- src/components/Select.module.scss
- src/components/Select.tsx
- src/components/SelectableContent.tsx
- src/styles/main.scss
Closes #190.
Hides the slot select in cases like these:
And only disable for `syncKey="language"` slots:
> chore: hide or disable select based on content

- ec.config.mjs
Something that has been bugging me was that we had line numbers on terminals and output. With this change, I'm restricting the Expressive Code Line Numbers plugin to only apply to some languages (see the array in the PR).
> fix: Only apply line numbers to some languages

- package-lock.json
- package.json
This makes the `@types/node` dependency explicit. I found that we were using outdated types and I needed something added in a newer version. By making it explicit, we can be in control of the version.
> deps: Explicitly depend upon Node.js types

- src/components/WhatAreArcjetUtilities.astro
- src/content/docs/redact/quick-start.mdx
- src/content/docs/redact/reference.mdx
Implements @davidmytton's suggestion from https://github.com/arcjet/arcjet-docs/pull/279/files#r1862108081 because it should be out-of-scope for that PR.
Let's get the wording and stuff resolved here and then pull it into the nosecone PR.
> feat: Add component describing Arcjet utilities

- package-lock.json
- package.json
- patches/typescript+5.7.2.patch
- src/components/DisplayType.astro
- src/content/docs/email-validation/reference.mdx
- src/content/docs/sensitive-info/reference.mdx
- src/content/docs/shield/reference.mdx
This introduces an Astro component that loads a module, extracts a specified type, simplifies it by one level, and then pretty-prints it.
This will ensure that our docs always match exported types from the SDK packages and can reduce the work needed to document large types like `NoseconeOptions`.
It doesn't work on all types because we might want to handwrite them in a simpler fashion, such as the `SensitiveInfoOptions`; this is common when we have heavy use of generics.
This work also highlighted some places where we should probably export types, such as `BotOptionsAllow` and `BotOptionsDeny`.
TypeScript has a hardcoded truncation length. It is [on their roadmap](https://github.com/microsoft/TypeScript/issues/59029), but in the meantime I introduced `patch-package` to update the value …
> feat: Introduce DisplayType component that outputs pretty-printed types

- src/components/DisplayType.astro
- src/lib/twoslasher.ts
When trying to use the new `DisplayType` component many time on a larger page resulted in a Out-Of-Memory crash. This was due to a new instance of twoslasher being created for each use. By moving it into a module, the singleton is reused by every instance and the OoM goes away.
> fix: Leverage twoslasher singleton to avoid OOM

- src/content/docs/ip.mdx
- src/lib/sidebars.ts
- src/snippets/ip/platform.ts
- src/snippets/ip/proxies.ts
- src/snippets/ip/usage.ts
Earlier this week, we discussed adding the `@arcjet/ip` utility to our Utilities section. I did a quick sketch at documenting it.
> feat: Add `@arcjet/ip` utility

- src/content/docs/nosecone/reference.mdx
- src/snippets/nosecone/quick-start/next-js/Step2.mdx
- src/snippets/nosecone/reference/next-js/ChainedMiddleware.js
- src/snippets/nosecone/reference/next-js/ChainedMiddleware.mdx
- src/snippets/nosecone/reference/next-js/ChainedMiddleware.ts
Following feedback in https://github.com/arcjet/arcjet-js/issues/2639
> chore: Add docs for chaining Nosecone middleware

- patches/typescript+5.7.3.patch
TypeScript was updated so `patch-package` was showing a warning on install. This migrates the patch.
> chore: Migrate typescript patch to avoid warning

- .devcontainer/devcontainer.json
I found that the json file was invalid due to a missing comma. However, the root user is not needed so I just disabled it in the devcontainer.
> chore: Disable root user in devcontainer

- src/components/DisplayType.astro
Closes #371 
Disabling the formatter made the Nosecone API docs pretty miserable to read due to no text wrapping.
Need to check in deploy preview because it doesn't crash in the dev server.
> fix: Re-enable prettier formatting

- src/content/docs/blueprints/payment-form.mdx
- src/content/docs/bot-protection/reference.mdx
- src/snippets/get-started/bun-hono/Step3.ts
- src/snippets/get-started/bun/BunServe.ts
- src/snippets/get-started/bun/Step3.js
- src/snippets/get-started/bun/Step3.ts
- src/snippets/get-started/deno/Step3.ts
- src/snippets/get-started/next-js/Step3App.js
- src/snippets/get-started/next-js/Step3App.ts
- src/snippets/get-started/next-js/Step3Pages.js
- src/snippets/get-started/next-js/Step3Pages.ts
- src/snippets/get-started/node-js-express/Express.js
- src/snippets/get-started/node-js-hono/Step3.ts
- src/snippets/get-started/node-js/Step3.js
- src/snippets/get-started/node-js/Step3.ts
- src/snippets/get-started/remix/Step3.tsx
- src/snippets/get-started/sveltekit/Step3.js
- src/snippets/get-started/sveltekit/Step3.ts
- src/snippets/sensitive-info/reference/nestjs/DecisionLog.ts
- src/snippets/signup-protection/quick-start/nestjs/Step3Controller.ts
This changes the remaining calls to `decision.reason.isSpoofed()`. While these are possible to use, they only make sense in a 1-rule context but all our examples show multiple rules being configured. To reduce footguns in our exampels, Spoofed and Verified checks should always be done against `results`.
Ref https://github.com/arcjet/arcjet-js/pull/3066#discussion_r1939951457
> chore: Change remaining `decision.reason.isSpoofed()` examples

- .github/dependabot.yml
The nosecone updates should be applied with the Arcjet updates because we version everything together right now.
> chore(ci): Group nosecone with Arcjet updates

- src/content/docs/bot-protection/identifying-bots.mdx
I was going to update these docs with changes to the structure that have occured (notably adding aliases, and ip verification).
However I realised that it is probably more effective to just link to the README.md since potential contributors
will need to go to the repo anyways, and having the same content in two places is likely to result in drift.
> docs(bots): replace known bots structure with reference

- src/snippets/reference/bun/ClientOverride.js
- src/snippets/reference/bun/ClientOverride.ts
- src/snippets/reference/bun/DecisionLog.js
- src/snippets/reference/bun/DecisionLog.ts
- src/snippets/reference/nestjs/IPLocation.ts
- src/snippets/reference/nextjs/IPLocationApp.js
- src/snippets/reference/nextjs/IPLocationApp.ts
- src/snippets/reference/nextjs/IPLocationPages.js
- src/snippets/reference/nextjs/IPLocationPages.ts
- src/snippets/reference/nodejs/IPLocation.js
- src/snippets/reference/nodejs/IPLocation.ts
- src/snippets/reference/remix/IPLocation.js
- src/snippets/reference/remix/IPLocation.ts
- src/snippets/reference/sveltekit/DecisionLog.js
- src/snippets/reference/sveltekit/DecisionLog.ts
I did a quick pass of the reference docs to see if any improvements could be made.
The ones I found were:
- We were checking for `.isBot()` in examples where there was no bot rule configured.
- We were returning a happy path response in some of our ip location examples before checking `isDenied`, I've changed these so that now we always check the decision first as you should do.
> docs: misc reference docs improvements

- src/components/badges/Free.astro
- src/content/docs/inspect.mdx
- src/lib/sidebars.ts
- src/snippets/inspect/usage.ts
Closes #437 
This adds API docs for the `@arcjet/inspect` utility package. I tried to highlight each function in the usage but that might become unwieldy as the package grows, but it should be fine for now.
I also added a `Free` component since we use this a lot in the project and the longer version causes MDX formatting problems. We can do some cleanup in a separate PR.
It was much easier to write these docs since we had already iterated on them in the doc comments of the PR so I see a lot of value in starting the docs in those blocks.
> feat: Add API documentation for `@arcjet/inspect` library

- src/components/badges/Enterprise.astro
- src/content/docs/bot-protection/reference.mdx
Follow up to https://github.com/arcjet/arcjet-docs/pull/439#issuecomment-2707343280
This updates an example about allowing bots to explain verification on well-behaved bots and leverages `isVerifiedBot` in `@arcjet/inspect`.
> chore: Update the verified example with `@arcjet/inspect`

- src/content/docs/rate-limiting/reference.mdx
- src/snippets/rate-limiting/reference/nextjs/PerRouteVsMiddleware.mdx
Replaces incorrect bot limit snippet examples from the rate limiting reference. Towards #448.
> remove duplicate content from rate limiting reference section.

- src/components/SdkReferenceLinkByFramework.astro
Updates the get-started sdk link for sveltekit.
Closes https://github.com/arcjet/arcjet-docs/issues/475
> fix: Use correct url on sveltekit sdk reference link card

- src/content/docs/reference/bun.mdx
- src/snippets/bot-protection/quick-start/bun/Step1.mdx
- src/snippets/email-validation/quick-start/bun/Step1.mdx
- src/snippets/get-started/bun-hono/Step1.mdx
- src/snippets/get-started/bun/Step1.mdx
- src/snippets/rate-limiting/quick-start/bun/Step1.mdx
- src/snippets/sensitive-info/quick-start/bun/Step1.mdx
- src/snippets/shield/quick-start/bun/Step1.mdx
- src/snippets/signup-protection/quick-start/bun/Step1.mdx
Closes #486
I've added a note below everywhere `bun add @arcjet/bun` appears in the docs (except hono getting started). Let me know if this placement & wording makes sense.
It's a fair amount of duplication at the moment but I didn't want to reinvent the wheel here.
> chore: Add note about @arcjet/bun compatibility with Bun's HTTP server

- src/content/docs/reference/astro.mdx
- src/lib/sidebars.ts
- src/snippets/get-started/astro/Step0.mdx
- src/snippets/get-started/astro/Step1.mdx
- src/snippets/reference/astro/ClientOverride.mjs
- src/snippets/reference/astro/Configuration.mjs
- src/snippets/reference/astro/DecisionLog.js
- src/snippets/reference/astro/DecisionLog.ts
- src/snippets/reference/astro/DecisionLogConfig.mjs
- src/snippets/reference/astro/ErrorHandling.js
- src/snippets/reference/astro/ErrorHandling.ts
- src/snippets/reference/astro/ErrorInspect.js
- src/snippets/reference/astro/ErrorInspect.ts
- src/snippets/reference/astro/IPLocation.js
- src/snippets/reference/astro/IPLocation.ts
- src/snippets/reference/astro/IPLocationConfig.mjs
- src/snippets/reference/astro/MultipleRules.mjs
- src/snippets/reference/astro/ProtectEndpoint.js
- src/snippets/reference/astro/ProtectEndpoint.ts
- src/snippets/reference/astro/ProtectMiddleware.js
- src/snippets/reference/astro/ProtectMiddleware.ts
- src/snippets/reference/astro/ProtectPage.astro
- src/snippets/reference/astro/Proxies.mjs
- src/snippets/reference/astro/RuleModesConfig.mjs
- src/snippets/reference/astro/WithRule.js
- src/snippets/reference/astro/WithRule.ts
Here is the Astro SDK reference documentation. I've taken the Next.js docs and adapted them for Astro.
Note that `TODO(#):` comments mean I will create issues and insert the number before merging.
cc @arcjet/design-team 
Closes #524
> feat(astro): Add Astro SDK reference documentation

- package-lock.json
- snippets/astro/astro.config.mjs
- snippets/astro/package.json
- snippets/astro/src/bot-detection/quick-start/Step3.mjs
- snippets/astro/src/bot-detection/quick-start/Step3.ts
- snippets/astro/src/config-base.mjs
- snippets/astro/src/reference/ProtectEndpoint.mjs
- snippets/astro/src/reference/ProtectEndpoint.ts
- snippets/astro/tsconfig.json
- src/content/docs/bot-protection/quick-start.mdx
- src/content/docs/get-started.mdx
- src/content/docs/reference/astro.mdx
- src/snippets/bot-protection/quick-start/astro/Step3.mdx
- src/snippets/bot-protection/quick-start/astro/Step4.mdx
- src/snippets/get-started/astro/Step0.mdx
- src/snippets/get-started/astro/Step3Config.js
- src/snippets/reference/astro/ClientOverride.mjs
- src/snippets/reference/astro/Configuration.mjs
- src/snippets/reference/astro/DecisionLogConfig.mjs
- src/snippets/reference/astro/IPLocationConfig.mjs
- src/snippets/reference/astro/MultipleRules.mjs
- src/snippets/reference/astro/Proxies.mjs
- src/snippets/reference/astro/RuleModesConfig.mjs
- src/snippets/shared/astro/Install.mdx
- src/snippets/shared/astro/InstallWithInspect.mdx
Here I've added the Quick Start documentation for Astro.
Additionally I've added npm workspaces with the eventual goal of moving all of the sample code to it's own workspace. The largest motivation for this is to remove some of the `dependencies` in the main `package.json` and simplify some of the work we're doing to make TypeScript happy (this was especially difficult with Astro, given the virtual modules and the docs already being an Astro project).
I'm also starting to think about a slightly different way to do code sharing along framework lines (the `shared` snippets folder).
Closes #518
> docs(astro): Add bot detection quick start for Astro

- .github/dependabot.yml
Closes #554 
#566 is failing due to zod, but we can't update to zod@4 yet because a boat load of packages rely on zod@3 still
> chore(dependabot): ignore zod 4 & remove reviewers

- package-lock.json
Resolve:
- https://github.com/arcjet/arcjet-docs/security/dependabot/62
> deps: update devalue past CVE-2025-57820

- src/content/docs/filters/reference.mdx
Documents this behavior. I verified this is how it works in code cc @wooorm-arcjet
> chore: show split expression example

- src/content/docs/signup-protection/reference.mdx
I also <kbd>cmd+f</kbd>d and could not find similar typos
> docs(signup-protection): fix typo

- src/content/docs/bot-protection/concepts.mdx
This commit “dog-foods” the recent filter feature instead of suggesting to write manual application code.
It also slightly rewords the prose.
Comments welcome on improving that!
(importantly, expand below this PR, as there is an alternative strategy there which supports different things than allow/deny)
> docs(bots): suggest `filters` to handle missing user agent
