src/content/docs/bot-protection/identifying-bots.mdx

Explains how we generate the known bots identifiers.

chore: Explain known bots repos

---

src/content/docs/troubleshooting.mdx

Solution for accidentially using the arcjet package rather than an adapter.

chore: Add troubleshooting for Error: Log is required / Error: Client is required

---

src/content/docs/bot-protection/identifying-bots.mdx

Suggested in https://github.com/arcjet/arcjet-docs/pull/66#discussion_r1757011344

docs: Update bot detection contribution instructions

---

src/content/docs/sensitive-info/reference/nodejs.mdx
src/content/docs/troubleshooting.mdx
src/snippets/sensitive-info/quick-start/nextjs/PerRouteApp.js
src/snippets/sensitive-info/quick-start/nextjs/PerRouteApp.ts
src/snippets/sensitive-info/quick-start/nextjs/PerRoutePages.js
src/snippets/sensitive-info/quick-start/nextjs/PerRoutePages.ts
src/snippets/sensitive-info/quick-start/nodejs/Step3.js
src/snippets/sensitive-info/quick-start/nodejs/Step3.ts
src/snippets/sensitive-info/quick-start/sveltekit/Step3.js
src/snippets/sensitive-info/quick-start/sveltekit/Step3.ts
src/snippets/sensitive-info/reference/nodejs/AccessBody.js
src/snippets/sensitive-info/reference/nodejs/AccessBody.ts

Closes https://github.com/arcjet/arcjet/issues/3059

chore: Improve the docs for how to consume the body in Express when using sensitiveInfo rules

---

package-lock.json
package.json
src/content/docs/troubleshooting.mdx
src/snippets/reference/nodejs/RequestFieldsExpress.ts

Explain how to create a custom request, which I had to do for https://github.com/arcjet/arcjet-js/issues/1754

chore: Explain custom Express request details

---

src/content/docs/sensitive-info/quick-start/nextjs.mdx
src/snippets/sensitive-info/quick-start/nextjs/PerRouteApp.js
src/snippets/sensitive-info/quick-start/nextjs/PerRouteApp.ts
src/snippets/sensitive-info/quick-start/nextjs/PerRoutePages.js
src/snippets/sensitive-info/quick-start/nextjs/PerRoutePages.ts
src/snippets/sensitive-info/reference/nextjs/ErrorsApp.js
src/snippets/sensitive-info/reference/nextjs/ErrorsApp.ts
src/snippets/sensitive-info/reference/nextjs/PerRouteApp.js
src/snippets/sensitive-info/reference/nextjs/PerRouteApp.ts

Fixes the Next.js examples for sensitive info so they work as copy/paste.

fix: Correct Next.js sensitive info examples

---

src/content/docs/index.mdx

Felt wrong to not have the section headings link to the sections. Fixed in this PR.

chore: make headings on the homepage link to the relevant sections

---

src/components/RenderFix.tsx
src/components/SelectableContent.tsx
src/components/SlotByFramework.scss
src/components/SlotByFramework.tsx
src/content/docs/get-started.mdx
src/styles/main.scss

Fix hydration issues that happen sporadically in React comps that have dynamic content.

fix: erratic react hydration

---

src/content/docs/integrations/authjs.mdx
src/content/docs/integrations/clerk.mdx
src/content/docs/integrations/openai.mdx
src/snippets/rate-limiting/reference/nextjs/Examples.mdx

Matching the changes in https://github.com/arcjet/arcjet-js/pull/2017

chore: Update example paths

---

package-lock.json
package.json

Resolving the dependabot alert.

chore: Override cookie dep to squash security notice

---

src/components/FrameworkSwitcher.tsx

Closes #126 
Changed this to always track framework selection which is beneficial for easy link sharing.

feat: track framework selection in query param

---

src/snippets/get-started/bun/Step4.mdx

fix: missing language switching block

---

src/components/Button.module.scss
src/components/Button.tsx
src/components/FrameworkLinks.module.scss
src/components/FrameworkLinks.tsx
src/content/docs/get-started.mdx

Adds a component to show framework shortcuts. This will hide itself when an `f=` query param is set. Closes #182.
Also adds foundational Button comp. Closes #129.

feat: add FrameworkLinks comp

---

astro.config.mjs
src/components/Block.tsx
src/components/Button.module.scss
src/components/Button.tsx
src/components/Hero.module.scss
src/components/Hero.tsx
src/components/Launch.module.scss
src/components/Launch.tsx
src/components/icons/ArrowRight.tsx
src/components/icons/LogoMarkSpark.tsx
src/components/overrides/Hero.astro
src/content/docs/index.mdx
src/styles/docs/index.scss
src/styles/main.scss

feat: revamp home hero and closing launch

---

package-lock.json
package.json
src/content/docs/blueprints/defining-custom-rules.mdx
src/content/docs/examples.mdx
src/lib/sidebars.ts
src/snippets/blueprints/CustomValidationRule.ts

This is a blueprint for defining custom local rules that will run in the Arcjet SDK rules engine.

feat: Add blueprint for defining custom rules

---

src/content/docs/email-validation/reference.mdx
src/content/docs/rate-limiting/quick-start.mdx
src/content/docs/signup-protection/reference.mdx

chore: Remove unused TextByFramework imports

---

src/content/docs/bot-protection/identifying-bots.mdx

This PR adds the structure of the known bots JSON file to the docs for the bot protection primitive.

docs: document known bots structure

---

src/components/Hero.module.scss
src/styles/main.scss

Adjust home layout following changes in #246.
https://github.com/user-attachments/assets/b6556b0a-c196-4ca6-a006-6df99776f6ba

chore: home layout sizing and responsiveness

---

package-lock.json
package.json
src/content/docs/integrations/clerk.mdx
src/snippets/integrations/ClerkNextJSAJMiddleware.ts
src/snippets/integrations/ClerkNextJSMiddleware.ts

See <https://clerk.com/docs/upgrade-guides/nextjs/v6>

chore: Update example for Clerk v6

---

src/content/docs/get-started.mdx

fix: Leverage defined component for remix install

---

src/content/docs/rate-limiting/reference.mdx
src/snippets/rate-limiting/reference/nestjs/Headers.mdx
src/snippets/rate-limiting/reference/nestjs/Headers.ts

Followup to <https://github.com/arcjet/arcjet-js/issues/2376>

chore: Show how to use decorate with NestJS

---

src/content/docs/get-started.mdx
src/content/docs/reference/nodejs.mdx
src/snippets/get-started/bun-hono/Step0.mdx
src/snippets/get-started/bun/Step0.mdx
src/snippets/get-started/deno/Step0.mdx
src/snippets/get-started/nest-js/Step0.mdx
src/snippets/get-started/next-js/Step0.mdx
src/snippets/get-started/node-js-express/Step0.mdx
src/snippets/get-started/node-js-hono/Step0.mdx
src/snippets/get-started/node-js/Step0.mdx
src/snippets/get-started/remix/Step0.mdx
src/snippets/get-started/sveltekit/Step0.mdx

Added the get started guide and link to the docs for the respective frameworks.

add instructions for creating a new project.

---

src/content/docs/rate-limiting/algorithms.mdx

fix: Clarify token bucket behavior

---

.devcontainer/devcontainer.json
src/content/docs/nosecone/reference.mdx

- **feat: Recommended extensions**
- **feat: Added Nosecone config examples**

feat: Nosecone example configs

---

src/content/docs/blueprints/sampling.mdx
src/content/docs/reference/bun.mdx
src/content/docs/reference/nestjs.mdx
src/content/docs/reference/nextjs.mdx
src/content/docs/reference/nodejs.mdx
src/content/docs/reference/remix.mdx
src/content/docs/reference/sveltekit.mdx
src/content/docs/shield/concepts.mdx
src/content/docs/shield/quick-start.mdx
src/content/docs/shield/reference.mdx
src/lib/sidebars.ts

Ref: https://github.com/arcjet/arcjet/issues/3770

chore: Naming Shield WAF

---

src/components/SdkReferenceLinkByFramework.astro
src/content/docs/bot-protection/quick-start.mdx
src/content/docs/email-validation/quick-start.mdx
src/content/docs/get-started.mdx
src/content/docs/ip.mdx
src/content/docs/nosecone/quick-start.mdx
src/content/docs/rate-limiting/quick-start.mdx
src/content/docs/redact/quick-start.mdx
src/content/docs/sensitive-info/quick-start.mdx
src/content/docs/shield/quick-start.mdx
src/content/docs/signup-protection/quick-start.mdx

Aligns the "What Next" section across different pages, also addressing #181.

feat: review closing sections on feature pages

---

astro.config.mjs
src/components/Select.module.scss
src/components/Select.tsx
src/components/ThemeSwitcher.module.scss
src/components/ThemeSwitcher.tsx
src/components/icons/ThemeFill.tsx
src/components/icons/ThemeStroke.tsx
src/components/icons/ThemeSystem.tsx
src/components/overrides/ThemeSelect.astro
src/styles/main.scss

Fix the select dropdown appearance for Windows/Linux OSs.
Closes #317.
Adds a custom `<ThemeSwitcher />`.
Closes #124.

fix: select dropdown appearance

---

src/snippets/signup-protection/quick-start/nextjs/Step3.mdx
src/snippets/signup-protection/quick-start/nextjs/Step3FormPages.jsx

The instruction text wasn't showing in the correct slot.
Reported in https://github.com/arcjet/arcjet-docs/discussions/392#discussioncomment-12001801

fix: Fix text showing up incorrectly

---

astro.config.mjs
src/components/TOC.module.scss
src/components/TOC.tsx
src/components/ThemeSwitcher.tsx
src/content.config.ts
src/content/i18n/en.json
src/lib/sidebars.ts
src/styles/main.scss
src/styles/partials/_vars.scss

- Refined visuals and interactions for sidebars.
- Refined visuals and interactions for the header.
- Add feature icons.
Closes #122.
Closes #131.

feat: visual and interaction improvements

---

src/content/docs/integrations/better-auth.mdx
src/lib/sidebars.ts

Docs for using Arcjet with Better Auth: https://github.com/arcjet/arcjet-js/pull/2750

feat: Better Auth integration

---

public/llms.txt

Follow guidance at https://llmstxt.org

feat: Add llms.txt

---

package-lock.json
package.json

See https://github.com/arcjet/arcjet-docs/security/dependabot/46

deps: bump multer past security alert

---

.gitignore
src/content/docs/architecture.mdx
src/content/docs/index.mdx

Adds the new video to Architecture and home.
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1210609447091346

feat: add How it works video

---

src/components/badges/Business.astro
src/components/badges/Starter.astro
src/content/docs/bot-protection/reference.mdx

Bot verification is on Starter.

fix: correct pricing plan

---

src/components/SDKVersionAstro.astro
src/content/docs/reference/astro.mdx

noted a find-and-replace typo, fixed it.
And, looks like the badges are all the same? 🤔

docs(astro): fix typo

---

src/snippets/rate-limiting/reference/nextjs/FixedWindowCustomCharacteristicFingerprintRule.ts

Fix non-existent characteristic
Closes #578

chore: Replace incorrect `req.ip` with `ip.src`
